# *****************************************************
# |docname| - Configure containerize Docker application
# *****************************************************
version: '3'

services:

  jobe:
    image: runestone/jobeinabox
    build: ./jobeinabox/
    volumes:
      - ./jobeinabox/files:/usr/local/lib/java

  runestone:
    image: runestone/server
    restart: always
    links:
      - jobe
    ports:
      - "80:80"
      - "443:443"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      WEB2PY_CONFIG: ${SERVER_CONFIG}
      BOOK_SERVER_CONFIG: ${SERVER_CONFIG}
      WEB2PY_MIGRATE: 'Yes'
      POSTGRES_HOST: ${POSTGRES_HOST}
      REDIS_HOST: ${REDIS_HOST}
      DBURL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}'
      DEV_DBURL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}_dev'
      TEST_DBURL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}_test'
      REDIS_URI: 'redis://${REDIS_HOST}:6379/0'
      RUNESTONE_HOST: '${RUNESTONE_HOST}'
      CERTBOT_EMAIL: '${CERTBOT_EMAIL}'
